version: '3.2'

services:
  postgres:
    image: postgres:15.1
    container_name: Postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "coolpassword"
    volumes:
      - Postgres:/var/lib/postgresql/data
    networks:
      - backcw
  
  app:
    build:
      context: .
      dockerfile: BackCW/Dockerfile
    container_name: App
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:80"
      DbConnectionString: "User ID=postgres;Password=coolpassword;Host=postgres;Pooling=true;"
    networks:
      - backcw

volumes:
  Postgres:

networks:
  backcw:
    external: true